# Ubuntu 12.04 LTS, ebs store
# Taken from http://cloud-images.ubuntu.com/locator/ec2/

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provision :shell, :path => "../../../scripts/provisioning/ubuntu/bootstrap.sh"
  config.vm.provision :shell, :path => "../../../scripts/provisioning/build_lttng_git.sh"

  config.vm.provider :aws do |aws, override|
    
    arch = ENV['AWS_ARCH'] ? ENV['AWS_ARCH'] : "amd64"

    amis = { "ap-northeast-1" => { "amd64" => "ami-b99b09b8", "i386" => "ami-b79b09b6"},
    	     "ap-southeast-1" => { "amd64" => "ami-44135816", "i386" => "ami-46135814"},
    	     "ap-southeast-2" => { "amd64" => "ami-c526b4ff", "i386" => "ami-c726b4fd"},
	     "eu-west-1"      => { "amd64" => "ami-1babb06f", "i386" => "ami-19abb06d"},
	     "sa-east-1"      => { "amd64" => "ami-c705a1da", "i386" => "ami-c505a1d8"},
	     "us-east-1"      => { "amd64" => "ami-1b135e72", "i386" => "ami-07135e6e"},
	     "us-west-1"      => { "amd64" => "ami-1cf1db59", "i386" => "ami-f6ec70c6"},
	     "us-west-2"      => { "amd64" => "ami-f8ec70c8", "i386" => "ami-f6ec70c6"} }

    amis.each do | region, ami |
      aws.region_config region, :ami => ami[arch]
    end

    aws.instance_type = ENV['AWS_INST'] ? ENV['AWS_INST'] : "t1.micro"
    override.ssh.username = "ubuntu"
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :
