# Ubuntu 13.04, ebs store
# Taken from http://cloud-images.ubuntu.com/locator/ec2/

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provision :shell, :path => "../../../scripts/provisioning/ubuntu/bootstrap.sh"
  config.vm.provision :shell, :path => "../../../scripts/provisioning/build_lttng_git.sh"

  config.vm.provider :aws do |aws, override|
    
    arch = ENV['AWS_ARCH'] ? ENV['AWS_ARCH'] : "amd64"

    amis = { "ap-northeast-1" => { "amd64" => "ami-d5099ad4", "i386" => "ami-d3099ad2"},
    	     "ap-southeast-1" => { "amd64" => "ami-6af5bd38", "i386" => "ami-64f5bd36"},
    	     "ap-southeast-2" => { "amd64" => "ami-8332a0b9", "i386" => "ami-8d32a0b7"},
	     "eu-west-1"      => { "amd64" => "ami-c9d4cfbd", "i386" => "ami-cfd4cfbb"},
	     "sa-east-1"      => { "amd64" => "ami-752b8f68", "i386" => "ami-7b2b8f66"},
	     "us-east-1"      => { "amd64" => "ami-7d317314", "i386" => "ami-7b317312"},
	     "us-west-1"      => { "amd64" => "ami-bc052ff9", "i386" => "ami-b2052ff7"},
	     "us-west-2"      => { "amd64" => "ami-8ade42ba", "i386" => "ami-88de42b8"} }

    amis.each do | region, ami |
      aws.region_config region, :ami => ami[arch]
    end

    aws.instance_type = ENV['AWS_INST'] ? ENV['AWS_INST'] : "t1.micro"
    override.ssh.username = "ubuntu"
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :