# Ubuntu 12.10, ebs store
# Taken from http://cloud-images.ubuntu.com/locator/ec2/

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provision :shell, :path => "../../../scripts/provisioning/ubuntu/bootstrap.sh"
  config.vm.provision :shell, :path => "../../../scripts/provisioning/build_lttng_git.sh"

  config.vm.provider :aws do |aws, override|
    
    arch = ENV['AWS_ARCH'] ? ENV['AWS_ARCH'] : "amd64"

    amis = { "ap-northeast-1" => { "amd64" => "ami-6955c668", "i386" => "ami-6555c664"},
    	     "ap-southeast-1" => { "amd64" => "ami-2ce0a87e", "i386" => "ami-2ee0a87c"},
    	     "ap-southeast-2" => { "amd64" => "ami-0b039131", "i386" => "ami-1503912f"},
	     "eu-west-1"      => { "amd64" => "ami-47617a33", "i386" => "ami-45617a31"},
	     "sa-east-1"      => { "amd64" => "ami-1b5afe06", "i386" => "ami-195afe04"},
	     "us-east-1"      => { "amd64" => "ami-27591a4e", "i386" => "ami-25591a4c"},
	     "us-west-1"      => { "amd64" => "ami-c822088d", "i386" => "ami-ce22088b"},
	     "us-west-2"      => { "amd64" => "ami-94069ba4", "i386" => "ami-92069ba2"} }

    amis.each do | region, ami |
      aws.region_config region, :ami => ami[arch]
    end

    aws.instance_type = ENV['AWS_INST'] ? ENV['AWS_INST'] : "t1.micro"
    override.ssh.username = "ubuntu"
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :
